language: ruby
cache: bundler

rvm:
  # - 2.2
  # - 2.3
  - 2.4.0
  # - ruby-head
  # The Rubinii aren't installing properly on Travis :/
  # - rbx-2
  # - rbx

# matrix:
#   allow_failures:
#     # Ruby head failures aren't disastrous, because we won't support it until
#     # it's released, but it's good to be aware of.
#     - rvm: ruby-head

gemfile:
  - spec/gemfiles/Gemfile.current
  - spec/gemfiles/Gemfile.old
  # - spec/gemfiles/Gemfile.older
  # - spec/gemfiles/Gemfile.oldest

before_install:
  # Stop all running Postgreses, so we don't get port conflicts when installing
  # a new version.
  - sudo /etc/init.d/postgresql stop

  # Make sure that 9.6 is installed, and stop it if it was just started.
  - sudo apt-get install postgresql-9.6
  - sudo /etc/init.d/postgresql stop

  # Postgres 9.6 won't have a proper pg_hba set up, so...
  - sudo mkdir -p /etc/postgresql/9.6/main
  - sudo cp -v /etc/postgresql/9.{5,6}/main/pg_hba.conf

  # Hook up the various Postgres versions to specific ports.
  - sudo sed -i "s/port = ..../port = 5432/g" /etc/postgresql/9.3/main/postgresql.conf
  - sudo sed -i "s/port = ..../port = 5433/g" /etc/postgresql/9.4/main/postgresql.conf
  - sudo sed -i "s/port = ..../port = 5434/g" /etc/postgresql/9.5/main/postgresql.conf
  - sudo sed -i "s/port = ..../port = 5435/g" /etc/postgresql/9.6/main/postgresql.conf

  # Start up the Postgres instances we care about.
  - sudo /etc/init.d/postgresql start 9.3 9.4 9.5 9.6

  # 9.6 won't have a travis user, so create one.
  - sudo -u postgres createuser -p 5435 -S -D -R travis

before_script:
  - psql -c 'create database "que-test"' -U postgres -p 5432
  - psql -c 'create database "que-test"' -U postgres -p 5433
  - psql -c 'create database "que-test"' -U postgres -p 5434
  - psql -c 'create database "que-test"' -U postgres -p 5435

script:
  # Run the complete test suite for each Postgres version:
  - DATABASE_URL=postgres://postgres:@localhost:5432/que-test bundle exec rake
  - DATABASE_URL=postgres://postgres:@localhost:5433/que-test bundle exec rake
  - DATABASE_URL=postgres://postgres:@localhost:5434/que-test bundle exec rake
  - DATABASE_URL=postgres://postgres:@localhost:5435/que-test bundle exec rake

notifications:
  email: false
